// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  version: env['npm_package_version'],
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
  firebase: {
    apiKey: 'AIzaSyC-IbgG3vlLhVmhJ0hus8XGBhjsUZxBdKI',
    authDomain: 'appexample-b5ff2.firebaseapp.com',
    projectId: 'appexample-b5ff2',
    storageBucket: 'appexample-b5ff2.appspot.com',
    messagingSenderId: '809106631927',
    appId: '1:809106631927:web:f52a1319786d2ee0d8f7f2',
  },
};
